/**
 * Proves the TypeScript inference port agrees with scikit-learn.
 *
 * The fixtures are generated by the trainers in `ml/`: each case holds a raw
 * input (a customer record, an SMS, a plot summary) alongside the answer
 * scikit-learn itself gave for it. Nothing here re-derives the expected value,
 * so a drift in the tokenizer, the tree walk or the packed-array decoding
 * fails the suite rather than quietly changing predictions in production.
 */

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import type { TaskMeta, WeightsBundle } from "../shared/types";
import { TabularEncoder, TfidfVectorizer } from "../worker/ml/features";
import { loadModel } from "../worker/ml/models";
import type { FeatureVector } from "../worker/ml/vector";

interface ParityCase {
  input: { text?: string } & Record<string, string | number>;
  expected: Record<
    string,
    { predictedIndex: number; probabilities?: number[]; scores?: number[] }
  >;
}

function read<T>(relativePath: string): T {
  return JSON.parse(
    readFileSync(fileURLToPath(new URL(relativePath, import.meta.url).href), "utf8"),
  ) as T;
}

function loadTask(task: string) {
  const meta = read<TaskMeta>(`../public/models/${task}.meta.json`);
  const weights = read<WeightsBundle>(`../public/models/${task}.weights.json`);
  const cases = read<{ cases: ParityCase[] }>(`./fixtures/${task}.parity.json`).cases;

  const vectorizer = weights.vectorizer ? new TfidfVectorizer(weights.vectorizer) : null;
  const encoder = meta.input.kind === "tabular" ? new TabularEncoder(meta.input) : null;

  const toVector = (input: ParityCase["input"]): FeatureVector => {
    if (vectorizer) return vectorizer.transform(input.text as string);
    if (!encoder) throw new Error(`task ${task} has no feature pipeline`);
    return encoder.encode(input);
  };

  return { meta, weights, cases, toVector };
}

/**
 * How close the port has to be, by estimator family.
 *
 * Tree ensembles carry their split points and leaf values at full float64, so
 * they reproduce scikit-learn to rounding error -- the measured worst case is
 * 2e-16 for the forest and 9e-12 for gradient boosting.
 *
 * Linear and Naive Bayes weights are stored as float32 (or rounded to six
 * decimals when the array is small enough to stay plain JSON), which buys a
 * roughly 2x smaller artifact for ~1e-7 of precision. Measured worst case
 * across all fixtures is 4.5e-7, so 5e-6 leaves an order of magnitude of
 * headroom while still failing loudly on a real regression.
 */
const EXACT_FAMILIES = new Set(["forest", "gbdt"]);
const TOLERANCE_EXACT = 1e-9;
const TOLERANCE_QUANTISED = 5e-6;

describe.each(["churn", "spam", "movie-genre"])("%s", (task) => {
  const { meta, weights, cases, toVector } = loadTask(task);

  it("ships weights for every advertised model", () => {
    expect(meta.modelIds.length).toBeGreaterThan(0);
    for (const id of meta.modelIds) expect(weights.models[id]).toBeDefined();
  });

  it("has fixtures to check against", () => {
    expect(cases.length).toBeGreaterThan(20);
  });

  for (const modelId of meta.modelIds) {
    describe(modelId, () => {
      const artifact = weights.models[modelId];
      const model = loadModel(artifact);
      const tolerance = EXACT_FAMILIES.has(artifact.type)
        ? TOLERANCE_EXACT
        : TOLERANCE_QUANTISED;

      it("reproduces every scikit-learn label", () => {
        const disagreements: string[] = [];
        for (const [index, testCase] of cases.entries()) {
          const expected = testCase.expected[modelId];
          const actual = model.predict(toVector(testCase.input));
          if (actual.predictedIndex !== expected.predictedIndex) {
            disagreements.push(
              `case ${index}: expected ${meta.classes[expected.predictedIndex]}, ` +
                `got ${meta.classes[actual.predictedIndex]}`,
            );
          }
        }
        expect(disagreements).toEqual([]);
      });

      it("reproduces scikit-learn's probabilities", () => {
        let worst = 0;
        let checked = 0;
        for (const testCase of cases) {
          const expected = testCase.expected[modelId];
          if (!expected.probabilities) continue;
          const actual = model.predict(toVector(testCase.input));
          expect(actual.probabilities).not.toBeNull();
          for (const [index, value] of expected.probabilities.entries()) {
            worst = Math.max(worst, Math.abs((actual.probabilities as number[])[index] - value));
          }
          checked += 1;
        }
        if (checked === 0) {
          // An uncalibrated SVM has no probabilities; its margin is checked below.
          expect(model.predict(toVector(cases[0].input)).probabilities).toBeNull();
          return;
        }
        expect(worst).toBeLessThan(tolerance);
      });

      it("reproduces scikit-learn's decision scores", () => {
        let worst = 0;
        let checked = 0;
        for (const testCase of cases) {
          const expected = testCase.expected[modelId];
          if (!expected.scores) continue;
          const actual = model.predict(toVector(testCase.input));
          for (const [index, value] of expected.scores.entries()) {
            worst = Math.max(worst, Math.abs(actual.scores[index] - value));
          }
          checked += 1;
        }
        if (checked === 0) return;
        expect(worst).toBeLessThan(tolerance);
      });
    });
  }
});
